version: '3.9'

services:
  note-taker:
    image: note-taker
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: sh -c "bin/note-taker db create && bin/note-taker db migrate && bin/note-taker start"
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "3000:8080"
    volumes:
      - ../open-api:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yml

volumes:
  postgres_data:
